-- Create notifications table (if not exists)
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity not null,
  title text not null,
  description text not null,
  type_id bigint not null,
  usr_id bigint not null,
  created_at timestamp with time zone not null default now(),
  read boolean not null default false,
  constraint notifications_pkey primary key (id)
) TABLESPACE pg_default;

-- Note: add FK constraints to your notification_types and users tables if desired.
